// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDixxloNSUu7yWnNY9Vh8TvdwsQ2K40GIk',
    appId: '1:389234181251:web:2a1685e2fc67cda6de07b6',
    messagingSenderId: '389234181251',
    projectId: 'ecotracker-49646',
    authDomain: 'ecotracker-49646.firebaseapp.com',
    storageBucket: 'ecotracker-49646.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfalWGvn8Wx2Qv3WXnYgeEdo3l13dnOoI',
    appId: '1:389234181251:android:af618fe46003d000de07b6',
    messagingSenderId: '389234181251',
    projectId: 'ecotracker-49646',
    storageBucket: 'ecotracker-49646.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDixxloNSUu7yWnNY9Vh8TvdwsQ2K40GIk',
    appId: '1:389234181251:web:351c31abf40b87e6de07b6',
    messagingSenderId: '389234181251',
    projectId: 'ecotracker-49646',
    authDomain: 'ecotracker-49646.firebaseapp.com',
    storageBucket: 'ecotracker-49646.firebasestorage.app',
  );
}
